title: Mijn coole site
email: harmenstoppels@gmail.com
description: Hoi
baseurl: ""
url: ""

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - tests

collections:
  activiteiten:
    output: true